name: spotify

on:
  push:
    branches: [main, master, dev]
    paths:
      - 'spotify/**'
      - '.github/workflows/spotify.yml'
  pull_request:
    branches: [main, master, dev]
    paths:
      - 'spotify/**'
      - '.github/workflows/spotify.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tools
        run: |
          sudo apt-get update
          npm install -g prettier

      - name: Prettier Check
        run: |
          prettier --config .prettierrc.json --check "spotify/**/*.js"

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: spotify/terraform

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: spotify/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: spotify/terraform

  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_SPOTIFY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: spotify/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: spotify/terraform
